lokasi_values = [
                "pulau kemaro",
                "Sungai Musi",
                "kambang iwak",
                "Punti Kayu",
                "Kantor Walikota",
                "Jembatan ampera",
                "Benteng Kuto Besak",
                "Bukit Siguntang",
                "Museum Balaputra Dewa",
                "Museum SMB 2",
                "Monumen Perjuangan Rakyat",
                "Masjid Agung",
                "Masjid Ki Marogan",
                "Masjid lawang Kidul",
                "Masjid pulau Seribu",
                "Masjid Al Mahmudiyah",
                "Makam Kambang Koci",
                "Makam Kawah Tekurep",
                "Masjid Sultan Agung",
                "Makam Sabokingking",
                "Makam Ratu Bagus Kuning",
                "Makam Candi welan",
                "Makam Ki Gede Ing Suro",
                "Makam Sultan M.Mansyur",
                "Makam Ariodillah",
                "Rumah Limas CekMas",
                "Rumah Lintas Bayumi Wahab",
                "Kawasan Pemakaman Islam Ilir",
                "Kawasan Pasar 16 Ilir",
                "Kawasan Tuan kentang",
                "Kawasan Sungai Lumpur darat",
                "Kawasan Sekanak sidewalk",
                "Kampung Songket",
                "kampung Palembang basuki rachmat",
                "Kelenteng Kwan Im",
                "Kampung Kapitan",
                "Kampung Arab Al-Munawar",
                "Pabrik Es Assegaf 16 Ulu",
                "Rumah-Rumah Adat di Dekranasda",
                "bunker pertahan jepang jalan joko",
                "lorong Goa Jepang AKBP H. Umar",
                "Taman Wisata Kerajaan Sriwijaya",
                "Museum Textil",
                "Museum Dr. A. K. Gani",
                "Masjid Suro",
                "Kebon Gede ",
                "Roemah Limas Kampoeng Arab",
                "Lawang Borotan",
                "gedung balai pertemuan",
                "Jakabaring Sport City",
                "Ampera Skate Park",
                "OPI Water Fun",
                "Amanzi Water Park",
                "Danau OPI",
                "Al Quran Al-Akbar",
                "Palembang Bird Park",
                "Masjid Cheng Ho",
                "PT. PUSRI",
                "PT. PERTAMINA",
                "zainal songket",
                "Rumah Limas palembang demang",
                "Kampung kreatif lebong gajah",
                "Kampung wisata anyaman",
                "Monumen Peringatan Penerbangan",
                "Kampung Bercorak / Warna Warni",
                "Miniatur Ka'bah Asrama Haji",
                "Kampung Hias Lorong Mari",
                "Goedang Boen Tjit",
                "Tugu Belido",
                "Tepian Sungai Sekanak Besolek",
                "Sentral Kampung Pempek",
                "Rumah Saudagar Ong Boen Tjit",
                "Pasar Durian Kuto",
                "TEKAK Galeri Ikan Hias",
                "Graha Sriwijaya",
                "Kawasan Wisata Lebak Cindo",
                "Kampung Kreatif Sugih Waras",
                
]
